import type { Metadata } from 'next'
import '@/css/_tailwind_.css'
import '@/css/_resets_.css'
import '@/css/_globals_.css'
import { Children } from '@/types/helpers'
import { FC, ReactNode } from 'react'
import Link from 'next/link'

import { Nunito_Sans, Abril_Fatface, Roboto } from 'next/font/google'

export const metadata: Metadata = {
   title: 'Lukasz Portfolio',
   description: 'Generated by create next app',
}
const roboto = Roboto({
   weight: ['400', '700'],
   style: ['normal', 'italic'],
   subsets: ['latin'],
   display: 'swap',
})

// const nunito = Nunito_Sans({
//    // subsets: ['latin'],
//    subsets: ['latin'],
//    display: 'swap',
//    preload: true,
//    // variable: '--font-nunito',
//    // weight: ["400", "700", "900"],
// })

// const abril = Abril_Fatface({
//    // subsets: ['latin'],
//    subsets: ['latin-ext'],
//    // variable: '--font-abril',
//    // weight: ["400"],
// })

const RootLayout = ({ children }: Children) => {

   console.log('root layout rendered, why did you rendered twice?')

   console.log('nunito => ', roboto)

   return (
      <html lang="en" className={roboto.className}>
         <head>
            <link rel="preconnect" href="https://fonts.gstatic.com" />
         </head>
         <body className={`${roboto.className} min-h-screen w-100% bg-dark`}>
            <main className='min-h-[100vh] tc-white'>
               {/* <Navbar /> */}
               {/* {navbar} */}
               <div className='min-h-screen fc'>
                  <div className='flex-grow'>
                     <nav className='bc-white br-5. px-16. py-5. g-16. frcc m-a w-min mt-12.'>
                        <Link href='/'>Home</Link>
                        <Link href='/rooms'>Rooms</Link>
                     </nav>
                     {children}
                     {/* {footer} */}
                  </div>
               </div>
            </main>
         </body>
      </html>
   )
}

export default RootLayout
