'use client'

import type { Metadata } from 'next'
import { nunito, abril } from './typography'
import '@/css/_tailwind_.css'
import '@/css/_resets_.css'
import '@/css/_globals_.css'
import { Children } from '@/types/helpers'
import { FC, ReactNode } from 'react'
// import Navbar from '@/_sections_/navbar/Navbar'
import Footer from '@/_sections_/footer/Footer'
import Link from 'next/link'

export const metadata: Metadata = {
   title: 'Lukasz Portfolio',
   description: 'Generated by create next app',
}

const RootLayout: FC<Children & { footer: ReactNode }> = ({ children, footer }) => {

   console.log('root layout rendered, why did you rendered twice?')

   return (
      <html lang="en">
         <body className={`${nunito.variable} ${abril.variable} min-h-screen w-100% bg-dark`}>
            <main className='min-h-[100vh] tc-white'>
               {/* <Navbar /> */}
               {/* {navbar} */}
               <div className='min-h-screen fc'>
                  <div className='flex-grow'>
                     <nav className='bc-white br-5. px-16. py-5. g-16. frcc m-a w-min mt-12.'>
                        <Link href='/'>Home</Link>
                        <Link href='/rooms'>Rooms</Link>
                     </nav>
                     {children}
                     {/* {footer} */}
                  </div>
                  <Footer />
               </div>
            </main>
         </body>
      </html>
   )
}

export default RootLayout
