import type { Metadata } from 'next'
import { nunito, abril } from './typography'
import '@/css/_tailwind_.css'
import '@/css/_resets_.css'
import '@/css/_globals_.css'
import { Children } from '@/types/helpers'

export const metadata: Metadata = {
   title: 'Lukasz Portfolio',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Children) {
   return (
      <html lang="en">
         <body className={`${nunito.variable} ${abril.variable}`}>
            {children}
         </body>
      </html>
   )
}
